# Generated by Django 4.2.2 on 2023-06-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trolleybus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='trolleybus_images')),
            ],
        ),
    ]
